enterpriseSearch.enabled: false
xpack.canvas.enabled: false
xpack.cloudSecurityPosture.enabled: false
xpack.reporting.enabled: false
xpack.securitySolution.enabled: false
xpack.watcher.enabled: false

uiSettings.overrides.defaultRoute: /app/observability/overview
